### ISSUE TITLE
running on docker?

### ISSUE THREAD

**Issue by ser** [dreezey/keycloak-argon2-password-hash-provider#10]
Is there any way to use this module on current docker version of keycloak?

**Comment by ser** [comment]
OK, after some research i found the solution. I mapped a docker volume in this way:

```
--volume /zfs/DATA/keycloak/argon2-password-hash-provider-2.0.1.jar:/opt/keycloak/providers/argon2-password-hash-provider-2.0.1.jar 
```

and everything works!

**Comment by dreezey** [comment]
Hi @ser , thanks for the solution and glad everything works in the container version as well.
